### ISSUE TITLE
Nothing much

### ISSUE THREAD

**Issue by Cyberkingcr7** [PlainDevelopment/discord-bot-eco#1]
Hi may i speak to the developer about something important

**Comment by breftejk** [comment]
Yeah, hello.
If its too private, join our Discord and contact Plain

**Comment by PlainDevelopment** [comment]
https://discord.gg/EdJFwNvNS9

**Comment by Cyberkingcr7** [comment]
> Yeah, hello. If its too private, join our Discord and contact Plain

thank you ill do so
