### ISSUE TITLE
Monthly function doesn't return false

### ISSUE THREAD

**Issue by CASPERg267** [PlainDevelopment/discord-bot-eco#3]
As i mentioned above monthly function doesn't return false even if the timeout hasn't expire yet

Leaderboard and shop functions need some editings to make it easier for module user to sort the data
or just add examples of how to do it

docs needs some more details about (rob - hasItem - leaderboard)

**Comment by Cyberkingcr7** [comment]
Same problem

**Comment by breftejk** [comment]
https://github.com/PlainDevelopment/discord-bot-eco/pull/4 (closed)

**Comment by PlainDevelopment** [comment]
discord-bot-eco@1.4.0
This update resolves the monthly timeout issues.

Regarding the leaderboard, you can splice the amount you want as shown below.
```
leaderboard.splice(0, 3) // TOP 3
leaderboard.splice(0, 5) // TOP 5
leaderboard.splice(0, 10) // TOP 10

```
